[workspace]
resolver = "2"
members = [
    "crates/rein",
    "crates/rein-macros",
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-or-later"
authors = ["Eric Lee <42969110+lyr1cs@users.noreply.github.com>"]

[workspace.dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
inventory = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
